import mongoose from 'mongoose';

// ── Sub-schemas ───────────────────────────────────────────────────────────────

const topicPlanSchema = new mongoose.Schema(
  {
    subject: {
      type: String,
      required: [true, 'Subject is required'],
      trim: true,
    },
    topic: {
      type: String,
      required: [true, 'Topic is required'],
      trim: true,
    },
    targetDate: {
      type: Date,
      required: [true, 'Target date is required'],
    },
    estimatedHours: {
      type: Number,
      min: 0.5,
      max: 24,
      default: 2,
    },
    isCompleted: {
      type: Boolean,
      default: false,
    },
    completedAt: {
      type: Date,
      default: null,
    },
    resources: {
      type: [String], // URLs or resource identifiers
      default: [],
    },
  },
  { _id: true },
);

const weekPlanSchema = new mongoose.Schema(
  {
    weekNumber: {
      type: Number,
      required: true,
      min: 1,
    },
    startDate: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      required: true,
    },
    topics: {
      type: [topicPlanSchema],
      default: [],
    },
    weeklyGoalHours: {
      type: Number,
      default: 0,
    },
    isCompleted: {
      type: Boolean,
      default: false,
    },
  },
  { _id: true },
);

// ── Main schema ───────────────────────────────────────────────────────────────

const studyRoadmapSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User reference is required'],
    },

    exam: {
      type: String,
      required: [true, 'Exam type is required'],
      enum: {
        values: ['NEET', 'JEE', 'UPSC', 'CAT', 'SSC'],
        message: '{VALUE} is not a supported exam',
      },
    },

    examDate: {
      type: Date,
      required: [true, 'Exam date is required'],
      validate: {
        validator(date) {
          return date > new Date();
        },
        message: 'Exam date must be in the future',
      },
    },

    dailyHours: {
      type: Number,
      required: [true, 'Daily study hours is required'],
      min: [0.5, 'Minimum 0.5 hours per day'],
      max: [16, 'Maximum 16 hours per day'],
    },

    weeks: {
      type: [weekPlanSchema],
      default: [],
    },

    overallProgress: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },

    // The raw AI prompt response stored for audit/regeneration
    aiGeneratedAt: {
      type: Date,
      default: null,
    },

    // Weak areas the AI factored into this roadmap
    weakAreasFocused: {
      type: [String],
      default: [],
    },

    isActive: {
      type: Boolean,
      default: true,
    },

    // Version counter — incremented each time roadmap is regenerated by AI
    version: {
      type: Number,
      default: 1,
      min: 1,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform(_doc, ret) {
        delete ret.__v;
        return ret;
      },
    },
  },
);

// ── Indexes ───────────────────────────────────────────────────────────────────

// One active roadmap per user per exam
studyRoadmapSchema.index(
  { userId: 1, exam: 1, isActive: 1 },
  { unique: true, partialFilterExpression: { isActive: true } },
);

studyRoadmapSchema.index({ userId: 1, createdAt: -1 });
studyRoadmapSchema.index({ exam: 1 });
studyRoadmapSchema.index({ examDate: 1 });

// ── Pre-save: recalculate overall progress ────────────────────────────────────

studyRoadmapSchema.pre('save', function (next) {
  if (!this.isModified('weeks')) return next();

  const allTopics = this.weeks.flatMap((w) => w.topics);
  const total = allTopics.length;

  if (total === 0) {
    this.overallProgress = 0;
    return next();
  }

  const completed = allTopics.filter((t) => t.isCompleted).length;
  this.overallProgress = Math.round((completed / total) * 100);

  // Mark week as completed if all topics done
  this.weeks.forEach((week) => {
    week.isCompleted =
      week.topics.length > 0 && week.topics.every((t) => t.isCompleted);
  });

  next();
});

// ── Virtuals ──────────────────────────────────────────────────────────────────

/**
 * Returns the total number of topics across all weeks.
 */
studyRoadmapSchema.virtual('totalTopics').get(function () {
  return this.weeks.reduce((sum, w) => sum + w.topics.length, 0);
});

/**
 * Returns the number of days remaining until the exam date.
 */
studyRoadmapSchema.virtual('daysRemaining').get(function () {
  if (!this.examDate) return null;
  const diff = this.examDate.getTime() - Date.now();
  return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
});

// ── Model export ──────────────────────────────────────────────────────────────

const StudyRoadmap = mongoose.model('StudyRoadmap', studyRoadmapSchema);
export default StudyRoadmap;
