import { Exam } from '../../core/models/question.model';

export interface ExamInfo {
  id: Exam;
  name: string;
  fullName: string;
  icon: string;
  colour: string;
  description: string;
}

export interface SubjectInfo {
  name: string;
  icon: string;
  topics: string[];
}

export const EXAM_LIST: ExamInfo[] = [
  {
    id: 'NEET',
    name: 'NEET',
    fullName: 'National Eligibility cum Entrance Test',
    icon: '🧬',
    colour: '#06D6A0',
    description: 'Medical & Dental Entrance',
  },
  {
    id: 'JEE',
    name: 'JEE',
    fullName: 'Joint Entrance Examination',
    icon: '⚙️',
    colour: '#118AB2',
    description: 'Engineering Entrance (IIT/NIT)',
  },
  {
    id: 'UPSC',
    name: 'UPSC',
    fullName: 'Union Public Service Commission',
    icon: '🏛️',
    colour: '#FFD166',
    description: 'Civil Services Examination',
  },
  {
    id: 'CAT',
    name: 'CAT',
    fullName: 'Common Admission Test',
    icon: '📊',
    colour: '#EF476F',
    description: 'MBA Entrance (IIM)',
  },
  {
    id: 'SSC',
    name: 'SSC',
    fullName: 'Staff Selection Commission',
    icon: '📋',
    colour: '#9B5DE5',
    description: 'Government Jobs (CGL/CHSL/MTS)',
  },
];

export const EXAM_SUBJECTS: Record<Exam, SubjectInfo[]> = {
  NEET: [
    {
      name: 'Physics',
      icon: '⚡',
      topics: [
        'Laws of Motion',
        'Work, Energy & Power',
        'Rotational Motion',
        'Gravitation',
        'Properties of Matter',
        'Thermodynamics',
        'Oscillations & Waves',
        'Electrostatics',
        'Current Electricity',
        'Magnetic Effects',
        'Electromagnetic Induction',
        'Optics',
        'Modern Physics',
        'Semiconductor Devices',
        'Communication Systems',
      ],
    },
    {
      name: 'Chemistry',
      icon: '🧪',
      topics: [
        'Some Basic Concepts',
        'Atomic Structure',
        'Chemical Bonding',
        'States of Matter',
        'Thermodynamics',
        'Equilibrium',
        'Redox Reactions',
        'Hydrogen',
        's-Block Elements',
        'p-Block Elements',
        'd & f Block Elements',
        'Coordination Compounds',
        'Organic Chemistry Basics',
        'Hydrocarbons',
        'Biomolecules',
        'Polymers',
        'Chemistry in Everyday Life',
      ],
    },
    {
      name: 'Biology',
      icon: '🌿',
      topics: [
        'The Living World',
        'Biological Classification',
        'Plant Kingdom',
        'Animal Kingdom',
        'Morphology of Flowering Plants',
        'Anatomy of Flowering Plants',
        'Structural Organisation in Animals',
        'Cell: The Unit of Life',
        'Cell Cycle and Division',
        'Biomolecules',
        'Photosynthesis',
        'Respiration in Plants',
        'Plant Growth and Development',
        'Digestion and Absorption',
        'Breathing and Exchange of Gases',
        'Body Fluids and Circulation',
        'Locomotion and Movement',
        'Neural Control and Coordination',
        'Chemical Coordination',
        'Reproduction in Organisms',
        'Sexual Reproduction in Flowering Plants',
        'Human Reproduction',
        'Reproductive Health',
        'Principles of Inheritance',
        'Molecular Basis of Inheritance',
        'Evolution',
        'Human Health and Disease',
        'Microbes in Human Welfare',
        'Biotechnology',
        'Ecosystem',
        'Biodiversity and Conservation',
        'Environmental Issues',
      ],
    },
  ],

  JEE: [
    {
      name: 'Physics',
      icon: '⚡',
      topics: [
        'Kinematics',
        'Laws of Motion',
        'Work, Energy & Power',
        'Rotational Motion',
        'Gravitation',
        'Properties of Solids & Liquids',
        'Thermodynamics',
        'Kinetic Theory of Gases',
        'Oscillations',
        'Waves',
        'Electrostatics',
        'Current Electricity',
        'Magnetic Effects of Current',
        'Electromagnetic Induction',
        'Alternating Currents',
        'Electromagnetic Waves',
        'Optics',
        'Dual Nature of Radiation',
        'Atoms & Nuclei',
        'Electronic Devices',
      ],
    },
    {
      name: 'Chemistry',
      icon: '🧪',
      topics: [
        'Mole Concept',
        'Atomic Structure',
        'Chemical Bonding',
        'States of Matter',
        'Chemical Thermodynamics',
        'Solutions',
        'Equilibrium',
        'Electrochemistry',
        'Chemical Kinetics',
        'Surface Chemistry',
        'Periodic Table',
        'p-Block Elements',
        'd & f Block',
        'Coordination Compounds',
        'Organic Chemistry',
        'Hydrocarbons',
        'Haloalkanes',
        'Alcohols & Phenols',
        'Carbonyl Compounds',
        'Amines',
        'Polymers',
        'Biomolecules',
      ],
    },
    {
      name: 'Mathematics',
      icon: '📐',
      topics: [
        'Sets, Relations & Functions',
        'Complex Numbers',
        'Matrices & Determinants',
        'Permutations & Combinations',
        'Binomial Theorem',
        'Sequences & Series',
        'Limits, Continuity & Differentiability',
        'Integral Calculus',
        'Differential Equations',
        'Coordinate Geometry',
        'Three Dimensional Geometry',
        'Vector Algebra',
        'Statistics & Probability',
        'Trigonometry',
        'Mathematical Reasoning',
      ],
    },
  ],

  UPSC: [
    {
      name: 'History',
      icon: '🏺',
      topics: [
        'Ancient Indian History',
        'Medieval Indian History',
        'Modern Indian History',
        'Indian National Movement',
        'Post-Independence India',
        'World History',
        'Art & Culture',
      ],
    },
    {
      name: 'Geography',
      icon: '🌍',
      topics: [
        'Physical Geography',
        'Indian Geography',
        'World Geography',
        'Economic Geography',
        'Human Geography',
        'Climatology',
        'Oceanography',
        'Disaster Management',
      ],
    },
    {
      name: 'Polity',
      icon: '⚖️',
      topics: [
        'Constitution of India',
        'Fundamental Rights & DPSP',
        'Parliament',
        'President & Executive',
        'Judiciary',
        'State Government',
        'Local Bodies',
        'Election System',
        'Emergency Provisions',
        'Constitutional Amendments',
      ],
    },
    {
      name: 'Economy',
      icon: '💹',
      topics: [
        'Macroeconomics Basics',
        'National Income',
        'Money & Banking',
        'Inflation',
        'Union Budget',
        'Five Year Plans',
        'Agriculture',
        'Industry & Services',
        'Foreign Trade',
        'International Organisations',
        'Poverty & Unemployment',
      ],
    },
    {
      name: 'Science & Technology',
      icon: '🔬',
      topics: [
        'Space Technology',
        'Defense Technology',
        'Biotechnology',
        'Nanotechnology',
        'IT & Cybersecurity',
        'Environment & Ecology',
        'Climate Change',
        'Energy Sources',
      ],
    },
    {
      name: 'Current Affairs',
      icon: '📰',
      topics: [
        'Government Schemes',
        'International Relations',
        'Awards & Honours',
        'Sports',
        'Reports & Indices',
        'Constitutional Bodies',
        'Committees & Commissions',
      ],
    },
  ],

  CAT: [
    {
      name: 'Verbal Ability',
      icon: '📝',
      topics: [
        'Reading Comprehension',
        'Para Jumbles',
        'Para Summary',
        'Odd Sentence Out',
        'Fill in the Blanks',
        'Grammar & Usage',
        'Vocabulary',
        'Critical Reasoning',
      ],
    },
    {
      name: 'Data Interpretation',
      icon: '📊',
      topics: [
        'Tables',
        'Bar Graphs',
        'Line Graphs',
        'Pie Charts',
        'Caselets',
        'Venn Diagrams',
        'Network Diagrams',
        'Data Sufficiency',
      ],
    },
    {
      name: 'Logical Reasoning',
      icon: '🧩',
      topics: [
        'Syllogisms',
        'Blood Relations',
        'Coding-Decoding',
        'Direction Sense',
        'Seating Arrangement',
        'Scheduling',
        'Binary Logic',
        'Games & Tournaments',
      ],
    },
    {
      name: 'Quantitative Aptitude',
      icon: '🔢',
      topics: [
        'Number System',
        'Arithmetic',
        'Algebra',
        'Geometry',
        'Mensuration',
        'Trigonometry',
        'Permutations & Combinations',
        'Probability',
        'Progressions',
        'Functions & Graphs',
      ],
    },
  ],

  SSC: [
    {
      name: 'English',
      icon: '🔤',
      topics: [
        'Reading Comprehension',
        'Error Detection',
        'Sentence Improvement',
        'Fill in the Blanks',
        'Cloze Test',
        'Synonyms & Antonyms',
        'Idioms & Phrases',
        'One Word Substitution',
        'Active/Passive Voice',
        'Direct/Indirect Speech',
      ],
    },
    {
      name: 'General Awareness',
      icon: '🌐',
      topics: [
        'History',
        'Geography',
        'Polity',
        'Economics',
        'Science & Technology',
        'Current Affairs',
        'Static GK',
        'Books & Authors',
        'Sports',
      ],
    },
    {
      name: 'Quantitative Aptitude',
      icon: '🔢',
      topics: [
        'Number System',
        'Ratio & Proportion',
        'Percentages',
        'Profit & Loss',
        'Simple & Compound Interest',
        'Time & Work',
        'Time, Speed & Distance',
        'Geometry',
        'Mensuration',
        'Algebra',
        'Trigonometry',
        'Data Interpretation',
      ],
    },
    {
      name: 'Reasoning',
      icon: '🧠',
      topics: [
        'Analogy',
        'Classification',
        'Series',
        'Coding-Decoding',
        'Blood Relations',
        'Direction Sense',
        'Matrix',
        'Syllogism',
        'Statement & Conclusion',
        'Non-Verbal Reasoning',
        'Venn Diagrams',
      ],
    },
  ],
};
